### PR TITLE
fix: use etch for view rendering

### PR DESCRIPTION
**Pull request by UziTech**
this is based on the WIP-6 branch

- add etch for rendering view
- add github actions
- add dependabot
- add atom-jasmine3-test-runner for tests

### CODE REVIEW

**Comment by vivi90** [comment]
Closes #6 and fixes #2.

**Comment by vivi90** [comment]
Still WIP.

**Comment by vivi90** [comment]
Closed accidentally by deleting the WIP-6 branch.

**Comment by vivi90** [comment]
Merged in WIP-6.

**Comment by UziTech** [comment]
WIP-6 should be good to merge into master. If you add an `ATOM_ACCESS_TOKEN` to secrets it will release v1.0.0 with semantic release.

**Comment by vivi90** [comment]
@UziTech Yes, looks good to me but still in the review. 

@UziTech, @sdinesh86 Sorry, not able to do this, because i have not enough rights for this repository.
But the `ATOM_ACCESS_TOKEN` is organization-wide configured, so it should work but for example with [atom-music](https://github.com/atom-extensions/atom-music) it has never released anything. Everytime i needed to do it manually. :-(

@UziTech Btw, why not using [atom-jasmine3-test-runner](https://www.npmjs.com/package/atom-jasmine3-test-runner) also for [atom-music](https://github.com/atom-extensions/atom-music)?

**Comment by vivi90** [comment]
@UziTech There is still an design bug, if i restart atom after usage of this plugin.
bug

**Comment by UziTech** [comment]
> why not using atom-jasmine3-test-runner also for atom-music?

We could I just haven't had time to change it.

> There is still an design bug, if i restart atom after usage of this plugin.

That doesn't happen on mine. It looks like it could be an issue with your theme. What theme are you using?

**Comment by vivi90** [comment]
> > why not using atom-jasmine3-test-runner also for atom-music?
> 
> We could I just haven't had time to change it.

Okay :slightly_smiling_face: 

> > There is still an design bug, if i restart atom after usage of this plugin.
> 
> That doesn't happen on mine. It looks like it could be an issue with your theme. What theme are you using?
I am using `One Dark` but it doesn't change, if i change the Theme.
Getting everytime in the element inspector this for the first one:
```html
<div class="row block inset-panel" style="background: rgba(0, 0, 0, 0) !important;">
```

**Comment by UziTech** [comment]
> it has never released anything. Everytime i needed to do it manually. :-(

It looks like that is because you release it manually before action completes so it stops. You do need to follow the [conventional commist guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary) in order for it to know which version to bump. Essentially `fix: ...` for patch `feat: ...` for minor and `BREAKING CHANGE` in the description for major bump.

**Comment by vivi90** [comment]
@UziTech Still can't identify the origin of this:
```html
... style="background: rgba(0, 0, 0, 0) !important;" ...
```

**Comment by UziTech** [comment]
It is nowhere in the dec-hex-oct-bin code so it must be from one of your other packages or your init file.

**Comment by vivi90** [comment]
@UziTech Init and Styles are clear. So maybe another package.
But now i want to make the design responsive but media queries are useless at this point..

**Comment by vivi90** [comment]
@UziTech Okay, i will implement it as a config value.

**Comment by vivi90** [comment]
@UziTech Okay, nearly finished but my usage of `refs` at line `34` and `36` in `dec-hex-oct-bin.js` doesn't work so i have pushed it again to `WIP-6`.

**Comment by UziTech** [comment]
I fixed it

**Pull request closed without merging**
